# Generated by Django 3.1.4 on 2021-08-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ad', 'Administrateur'), ('ve', 'Vendeur'), ('ag', 'Agent')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('cl', 'Client'), ('Fr', 'Fournisseur'), ('pr', 'Prospet')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(blank=True, choices=[('acc', 'Accepté'), ('fac', 'Facturé'), ('Ter', 'Terminé'), ('ann', 'Annullé'), ('env', 'Envoyé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Newsletter', 'Newsletter'), ('Youtube', 'Youtube'), ('Google', 'Google')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='state',
            field=models.CharField(blank=True, choices=[('act', 'Active'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(blank=True, choices=[('3', '3'), ('2', '2'), ('1', '1')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('ter', 'Terminé'), ('enp', 'En pause'), ('ann', 'Annulé'), ('aff', 'A faire')], max_length=3, null=True),
        ),
    ]
