# Generated by Django 3.1 on 2022-04-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20220425_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ve', 'Vendeur'), ('ag', 'Agent'), ('ad', 'Administrateur')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('cl', 'Client'), ('pr', 'Prospet'), ('Fr', 'Fournisseur')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(blank=True, choices=[('env', 'Envoyé'), ('ann', 'Annullé'), ('acc', 'Accepté'), ('fac', 'Facturé'), ('Ter', 'Terminé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseurs',
            name='fournisseur_type',
            field=models.CharField(choices=[('pa', 'Paticulier'), ('en', 'Entreprise')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Newsletter', 'Newsletter'), ('Google', 'Google'), ('Youtube', 'Youtube')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='state',
            field=models.CharField(blank=True, choices=[('act', 'Active'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('1', '1')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('ann', 'Annulé'), ('enc', 'En cours'), ('enp', 'En pause'), ('ter', 'Terminé'), ('aff', 'A faire')], max_length=3, null=True),
        ),
    ]
