# Generated by Django 3.1 on 2021-10-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20210908_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ag', 'Agent'), ('ad', 'Administrateur'), ('ve', 'Vendeur')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('pr', 'Prospet'), ('cl', 'Client'), ('Fr', 'Fournisseur')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(blank=True, choices=[('acc', 'Accepté'), ('Ter', 'Terminé'), ('fac', 'Facturé'), ('env', 'Envoyé'), ('ann', 'Annullé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Google', 'Google'), ('Newsletter', 'Newsletter'), ('Youtube', 'Youtube')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('aff', 'A faire'), ('enp', 'En pause'), ('ann', 'Annulé'), ('ter', 'Terminé'), ('enc', 'En cours')], max_length=3, null=True),
        ),
    ]
