# Generated by Django 3.1 on 2022-04-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20220428_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ad', 'Administrateur'), ('ag', 'Agent'), ('ve', 'Vendeur')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='categorie_client',
            field=models.CharField(blank=True, choices=[('p', 'Personne'), ('e', 'Entreprise')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('Fr', 'Fournisseur'), ('pr', 'Prospet'), ('cl', 'Client')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('Terme', 'A terme'), ('Virement', 'Virement'), ('Cash', 'Cash')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(blank=True, choices=[('Ter', 'Terminé'), ('env', 'Envoyé'), ('fac', 'Facturé'), ('acc', 'Accepté'), ('ann', 'Annullé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Newsletter', 'Newsletter'), ('Google', 'Google'), ('Youtube', 'Youtube')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='state',
            field=models.CharField(blank=True, choices=[('act', 'Active'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('ter', 'Terminé'), ('aff', 'A faire'), ('ann', 'Annulé'), ('enp', 'En pause')], max_length=3, null=True),
        ),
    ]
