# Generated by Django 3.1 on 2021-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20211005_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ve', 'Vendeur'), ('ad', 'Administrateur'), ('ag', 'Agent')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='categorie_client',
            field=models.CharField(blank=True, choices=[('e', 'Entreprise'), ('p', 'Personne')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('cl', 'Client'), ('pr', 'Prospet'), ('Fr', 'Fournisseur')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(blank=True, choices=[('acc', 'Accepté'), ('env', 'Envoyé'), ('fac', 'Facturé'), ('ann', 'Annullé'), ('Ter', 'Terminé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseurs',
            name='fournisseur_type',
            field=models.CharField(choices=[('en', 'Entreprise'), ('pa', 'Paticulier')], max_length=2),
        ),
        migrations.AlterField(
            model_name='note',
            name='state',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('act', 'Active')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(blank=True, choices=[('3', '3'), ('2', '2'), ('1', '1')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('ter', 'Terminé'), ('enp', 'En pause'), ('enc', 'En cours'), ('aff', 'A faire'), ('ann', 'Annulé')], max_length=3, null=True),
        ),
    ]
