# Generated by Django 3.1 on 2021-10-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20211011_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecteurActivite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Secteur',
                'verbose_name_plural': 'Secteurs',
            },
        ),
        migrations.AlterField(
            model_name='agent',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ag', 'Agent'), ('ad', 'Administrateur'), ('ve', 'Vendeur')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='categorie_client',
            field=models.CharField(blank=True, choices=[('e', 'Entreprise'), ('p', 'Personne')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('Fr', 'Fournisseur'), ('cl', 'Client'), ('pr', 'Prospet')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(blank=True, choices=[('env', 'Envoyé'), ('fac', 'Facturé'), ('Ter', 'Terminé'), ('ann', 'Annullé'), ('acc', 'Accepté')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseurs',
            name='fournisseur_type',
            field=models.CharField(choices=[('pa', 'Paticulier'), ('en', 'Entreprise')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Newsletter', 'Newsletter'), ('Google', 'Google'), ('Youtube', 'Youtube')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(blank=True, choices=[('3', '3'), ('1', '1'), ('2', '2')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('ann', 'Annulé'), ('aff', 'A faire'), ('ter', 'Terminé'), ('enp', 'En pause'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fournisseurs',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.secteuractivite'),
        ),
    ]
