# Generated by Django 3.1 on 2021-10-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_auto_20211011_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='categorie_client',
            field=models.CharField(blank=True, choices=[('p', 'Personne'), ('e', 'Entreprise')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('Fr', 'Fournisseur'), ('cl', 'Client'), ('pr', 'Prospet')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(blank=True, choices=[('acc', 'Accepté'), ('ann', 'Annullé'), ('env', 'Envoyé'), ('fac', 'Facturé'), ('Ter', 'Terminé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseurs',
            name='fournisseur_type',
            field=models.CharField(choices=[('en', 'Entreprise'), ('pa', 'Paticulier')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Google', 'Google'), ('Newsletter', 'Newsletter'), ('Youtube', 'Youtube')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('enp', 'En pause'), ('ann', 'Annulé'), ('enc', 'En cours'), ('aff', 'A faire'), ('ter', 'Terminé')], max_length=3, null=True),
        ),
    ]
