# Generated by Django 3.1 on 2021-10-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_auto_20211016_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('rep', 'Pause')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ad', 'Administrateur'), ('ve', 'Vendeur'), ('ag', 'Agent')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('pr', 'Prospet'), ('cl', 'Client'), ('Fr', 'Fournisseur')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(blank=True, choices=[('Ter', 'Terminé'), ('ann', 'Annullé'), ('env', 'Envoyé'), ('acc', 'Accepté'), ('fac', 'Facturé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseurs',
            name='fournisseur_type',
            field=models.CharField(choices=[('en', 'Entreprise'), ('pa', 'Paticulier')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Google', 'Google'), ('Youtube', 'Youtube'), ('Newsletter', 'Newsletter')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(blank=True, choices=[('1', '1'), ('3', '3'), ('2', '2')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('enp', 'En pause'), ('ter', 'Terminé'), ('aff', 'A faire'), ('ann', 'Annulé'), ('enc', 'En cours')], max_length=3, null=True),
        ),
    ]
