# Generated by Django 3.1 on 2021-10-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_auto_20211016_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('Fr', 'Fournisseur'), ('cl', 'Client'), ('pr', 'Prospet')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('rep', 'Pause'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Virement', 'Virement'), ('Terme', 'A terme')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(blank=True, choices=[('acc', 'Accepté'), ('fac', 'Facturé'), ('env', 'Envoyé'), ('ann', 'Annullé'), ('Ter', 'Terminé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(blank=True, choices=[('2', '2'), ('1', '1'), ('3', '3')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('aff', 'A faire'), ('ter', 'Terminé'), ('ann', 'Annulé'), ('enp', 'En pause'), ('enc', 'En cours')], max_length=3, null=True),
        ),
    ]
