# Generated by Django 3.1 on 2022-05-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_auto_20220501_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ag', 'Agent'), ('ve', 'Vendeur'), ('ad', 'Administrateur')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='categorie_client',
            field=models.CharField(blank=True, choices=[('p', 'Personne'), ('e', 'Entreprise')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('pr', 'Prospet'), ('Fr', 'Fournisseur'), ('cl', 'Client')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('sau', 'Sauvegarder'), ('rep', 'Pause'), ('bro', 'Brouillon'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Virement', 'Virement'), ('Terme', 'A terme')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(blank=True, choices=[('ann', 'Annullé'), ('acc', 'Accepté'), ('Ter', 'Terminé'), ('fac', 'Facturé'), ('env', 'Envoyé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseurs',
            name='fournisseur_type',
            field=models.CharField(choices=[('en', 'Entreprise'), ('pa', 'Paticulier')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Youtube', 'Youtube'), ('Newsletter', 'Newsletter'), ('Google', 'Google')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='state',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('act', 'Active')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='status',
            field=models.CharField(blank=True, choices=[('att', 'En attante'), ('con', 'Confirmé'), ('ann', 'Annulé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(blank=True, choices=[('2', '2'), ('1', '1'), ('3', '3')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('ann', 'Annulé'), ('enp', 'En pause'), ('aff', 'A faire'), ('enc', 'En cours'), ('ter', 'Terminé')], max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='AssignTache',
        ),
    ]
