# Generated by Django 3.1 on 2022-01-02 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_auto_20220102_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.secteuractivite'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ve', 'Vendeur'), ('ad', 'Administrateur'), ('ag', 'Agent')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='categorie_client',
            field=models.CharField(blank=True, choices=[('p', 'Personne'), ('e', 'Entreprise')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('pr', 'Prospet'), ('Fr', 'Fournisseur'), ('cl', 'Client')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('Terme', 'A terme'), ('Virement', 'Virement'), ('Cash', 'Cash')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(blank=True, choices=[('ann', 'Annullé'), ('fac', 'Facturé'), ('Ter', 'Terminé'), ('acc', 'Accepté'), ('env', 'Envoyé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Youtube', 'Youtube'), ('Google', 'Google'), ('Newsletter', 'Newsletter')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='state',
            field=models.CharField(blank=True, choices=[('act', 'Active'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(blank=True, choices=[('2', '2'), ('1', '1'), ('3', '3')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('ann', 'Annulé'), ('ter', 'Terminé'), ('aff', 'A faire'), ('enp', 'En pause'), ('enc', 'En cours')], max_length=3, null=True),
        ),
    ]
