# Generated by Django 3.1 on 2022-05-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_auto_20220509_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseurs',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ad', 'Administrateur'), ('ag', 'Agent'), ('ve', 'Vendeur')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('sau', 'Sauvegarder'), ('bro', 'Brouillon'), ('rep', 'Pause')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Terme', 'A terme'), ('Virement', 'Virement')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(blank=True, choices=[('ann', 'Annullé'), ('fac', 'Facturé'), ('acc', 'Accepté'), ('Ter', 'Terminé'), ('env', 'Envoyé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('ann', 'Annulé'), ('enp', 'En pause'), ('enc', 'En cours'), ('ter', 'Terminé'), ('aff', 'A faire')], max_length=3, null=True),
        ),
    ]
