# Generated by Django 3.1 on 2022-05-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_auto_20220510_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='id_comp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ve', 'Vendeur'), ('ag', 'Agent'), ('ad', 'Administrateur')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('Fr', 'Fournisseur'), ('pr', 'Prospet'), ('cl', 'Client')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('rep', 'Pause'), ('sau', 'Sauvegarder'), ('bro', 'Brouillon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(blank=True, choices=[('env', 'Envoyé'), ('fac', 'Facturé'), ('ann', 'Annullé'), ('Ter', 'Terminé'), ('acc', 'Accepté')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Newsletter', 'Newsletter'), ('Youtube', 'Youtube'), ('Google', 'Google')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='status',
            field=models.CharField(blank=True, choices=[('att', 'En attante'), ('con', 'Confirmé'), ('ann', 'Annulé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('aff', 'A faire'), ('ter', 'Terminé'), ('enc', 'En cours'), ('enp', 'En pause'), ('ann', 'Annulé')], max_length=3, null=True),
        ),
    ]
