# Generated by Django 3.1.4 on 2021-08-22 11:06

import commande.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '__first__'),
        ('leads', '0002_auto_20210822_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneBonCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_commande', models.CharField(blank=True, default=commande.models.increment_order_id, max_length=1000, null=True)),
                ('date_commande', models.DateField()),
                ('adresse_livraison', models.CharField(blank=True, max_length=1000, null=True)),
                ('observation', models.CharField(blank=True, max_length=1000, null=True)),
                ('delai_paiement', models.CharField(blank=True, choices=[('60j', '60 Jours'), ('atr', 'A terme'), ('30j', '30 Jours'), ('40j', '40 Jours')], max_length=3, null=True)),
                ('status', models.CharField(blank=True, choices=[('ann', 'Annuler'), ('val', 'Valider'), ('att', 'En attente'), ('con', 'Confirmer')], max_length=3, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('ligne_commande', models.ManyToManyField(to='commande.LigneBonCommande')),
            ],
        ),
    ]
