# Generated by Django 3.1 on 2021-09-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_auto_20210905_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('val', 'Valider'), ('att', 'En attente'), ('con', 'Confirmer'), ('ann', 'Annuler')], max_length=3, null=True),
        ),
    ]
