# Generated by Django 3.1 on 2021-09-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_auto_20210905_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('60j', '60 Jours'), ('atr', 'A terme'), ('40j', '40 Jours'), ('30j', '30 Jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('val', 'Valider'), ('con', 'Confirmer'), ('att', 'En attente')], max_length=3, null=True),
        ),
    ]
