# Generated by Django 3.1 on 2021-10-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_auto_20210908_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('atr', 'A terme'), ('30j', '30 Jours'), ('60j', '60 Jours'), ('40j', '40 Jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('con', 'Confirmer'), ('ann', 'Annuler'), ('att', 'En attente'), ('val', 'Valider')], max_length=3, null=True),
        ),
    ]
