# Generated by Django 3.1 on 2021-10-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_auto_20211004_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('30j', '30 Jours'), ('atr', 'A terme'), ('60j', '60 Jours'), ('40j', '40 Jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('con', 'Confirmer'), ('att', 'En attente'), ('val', 'Valider')], max_length=3, null=True),
        ),
    ]
