# Generated by Django 3.1 on 2021-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0006_auto_20211005_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('con', 'Confirmer'), ('val', 'Valider'), ('att', 'En attente'), ('ann', 'Annuler')], max_length=3, null=True),
        ),
    ]
