# Generated by Django 3.1 on 2021-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0008_auto_20211005_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('att', 'En attente'), ('ann', 'Annuler'), ('con', 'Confirmer'), ('val', 'Valider')], max_length=3, null=True),
        ),
    ]
