# Generated by Django 3.1 on 2021-10-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0009_auto_20211006_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('40j', '40 Jours'), ('atr', 'A terme'), ('30j', '30 Jours'), ('60j', '60 Jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('att', 'En attente'), ('con', 'Confirmer'), ('val', 'Valider')], max_length=3, null=True),
        ),
    ]
