# Generated by Django 3.1 on 2021-10-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0011_auto_20211007_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('60j', '60 Jours'), ('atr', 'A terme'), ('40j', '40 Jours'), ('30j', '30 Jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('con', 'Confirmer'), ('val', 'Valider'), ('att', 'En attente'), ('ann', 'Annuler')], max_length=3, null=True),
        ),
    ]
