# Generated by Django 3.1 on 2021-10-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0012_auto_20211007_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('atr', 'A terme'), ('40j', '40 Jours'), ('30j', '30 Jours'), ('60j', '60 Jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('att', 'En attente'), ('val', 'Valider'), ('con', 'Confirmer'), ('ann', 'Annuler')], max_length=3, null=True),
        ),
    ]
