# Generated by Django 3.1 on 2021-10-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0016_auto_20211011_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('con', 'Confirmer'), ('att', 'En attente'), ('val', 'Valider'), ('ann', 'Annuler')], max_length=3, null=True),
        ),
    ]
