# Generated by Django 3.1 on 2021-10-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0017_auto_20211012_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('30j', '30 Jours'), ('40j', '40 Jours'), ('60j', '60 Jours'), ('atr', 'A terme')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('val', 'Valider'), ('con', 'Confirmer'), ('ann', 'Annuler'), ('att', 'En attente')], max_length=3, null=True),
        ),
    ]
