# Generated by Django 3.1 on 2021-10-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0018_auto_20211016_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('40j', '40 Jours'), ('60j', '60 Jours'), ('30j', '30 Jours'), ('atr', 'A terme')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('val', 'Valider'), ('con', 'Confirmer'), ('att', 'En attente')], max_length=3, null=True),
        ),
    ]
