# Generated by Django 3.1 on 2021-10-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0022_auto_20211018_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('atr', 'A terme'), ('40j', '40 Jours'), ('60j', '60 Jours'), ('30j', '30 Jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('con', 'Confirmer'), ('val', 'Valider'), ('ann', 'Annuler'), ('att', 'En attente')], max_length=3, null=True),
        ),
    ]
