# Generated by Django 3.1 on 2022-01-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0023_auto_20211031_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('atr', 'A terme'), ('30j', '30 Jours'), ('60j', '60 Jours'), ('40j', '40 Jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('val', 'Valider'), ('att', 'En attente'), ('ann', 'Annuler'), ('con', 'Confirmer')], max_length=3, null=True),
        ),
    ]
