# Generated by Django 3.1 on 2022-01-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0026_auto_20220103_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('30j', '30 Jours'), ('60j', '60 Jours'), ('atr', 'A terme'), ('40j', '40 Jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('val', 'Valider'), ('att', 'En attente'), ('con', 'Confirmer')], max_length=3, null=True),
        ),
    ]
