# Generated by Django 3.1 on 2022-04-23 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_auto_20220423_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=2000, null=True)),
                ('nif', models.CharField(blank=True, max_length=100, null=True)),
                ('art', models.CharField(blank=True, max_length=100, null=True)),
                ('nrc', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='')),
                ('adresse1', models.CharField(blank=True, max_length=100, null=True)),
                ('nrue', models.CharField(blank=True, max_length=5, null=True)),
                ('province', models.CharField(blank=True, max_length=25, null=True)),
                ('etat', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=13, null=True)),
                ('mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('gestionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.agent')),
            ],
            options={
                'verbose_name': 'Mon entreprise',
                'verbose_name_plural': 'Mes entreprises',
            },
        ),
    ]
