# Generated by Django 3.1 on 2022-04-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0005_auto_20220428_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompany',
            name='niveau',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro.')], max_length=10, null=True),
        ),
    ]
