# Generated by Django 3.1 on 2022-04-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0008_auto_20220429_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycompany',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mycompany',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mycompany',
            name='niveau',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('free', 'Free'), ('pro', 'Pro.')], max_length=10, null=True),
        ),
    ]
