# Generated by Django 3.1 on 2022-04-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0010_auto_20220430_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompany',
            name='niveau',
            field=models.CharField(blank=True, choices=[('pro', 'Pro.'), ('basic', 'Basic'), ('free', 'Free')], max_length=10, null=True),
        ),
    ]
