# Generated by Django 3.1 on 2022-04-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0014_auto_20220430_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompany',
            name='niveau',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('free', 'Free'), ('pro', 'Pro.')], max_length=10, null=True),
        ),
    ]
