# Generated by Django 3.1 on 2022-04-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0015_auto_20220430_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompany',
            name='niveau',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('pro', 'Pro.'), ('free', 'Free')], max_length=10, null=True),
        ),
    ]
