# Generated by Django 3.1 on 2022-05-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0021_auto_20220502_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompany',
            name='niveau',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('free', 'Free'), ('pro', 'Pro.')], max_length=10, null=True),
        ),
    ]
