# Generated by Django 3.1 on 2022-05-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0022_auto_20220502_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompany',
            name='niveau',
            field=models.CharField(blank=True, choices=[('pro', 'Pro.'), ('free', 'Free'), ('basic', 'Basic')], max_length=10, null=True),
        ),
    ]
