# Generated by Django 3.1 on 2022-04-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_operation',
            field=models.CharField(blank=True, choices=[('e', 'Entrer'), ('s', 'Sortie')], max_length=2, null=True),
        ),
    ]
