# Generated by Django 3.1 on 2021-10-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_auto_20211005_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
