# Generated by Django 3.1 on 2022-04-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_auto_20220429_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_operation',
            field=models.CharField(blank=True, choices=[('s', 'Sortie'), ('e', 'Entrer')], max_length=2, null=True),
        ),
    ]
