# Generated by Django 3.1 on 2021-10-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_produit_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='hauteur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='cat_produit',
            field=models.CharField(blank=True, choices=[('srv', 'Service'), ('prd', 'Produits')], max_length=3, null=True),
        ),
    ]
