# Generated by Django 3.1 on 2021-10-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_auto_20211007_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
