# Generated by Django 3.1 on 2022-01-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0013_auto_20211018_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='cat_produit',
            field=models.CharField(blank=True, choices=[('prd', 'Produits'), ('srv', 'Service')], max_length=3, null=True),
        ),
    ]
