# Generated by Django 3.1 on 2022-01-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0014_auto_20220102_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='cat_produit',
            field=models.CharField(blank=True, choices=[('srv', 'Service'), ('prd', 'Produits')], max_length=3, null=True),
        ),
    ]
