# Generated by Django 3.1 on 2022-05-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0017_auto_20220430_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_operation',
            field=models.CharField(blank=True, choices=[('s', 'Sortie'), ('e', 'Entrer')], max_length=2, null=True),
        ),
    ]
