# Generated by Django 3.1 on 2022-05-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0018_auto_20220501_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='cat_produit',
            field=models.CharField(blank=True, choices=[('srv', 'Service'), ('prd', 'Produits')], max_length=3, null=True),
        ),
    ]
