# Generated by Django 4.1.5 on 2023-01-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0026_auto_20220512_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_operation',
            field=models.CharField(blank=True, choices=[('s', 'Sortie'), ('e', 'Entrer')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='cat_produit',
            field=models.CharField(blank=True, choices=[('srv', 'Service'), ('prd', 'Produits')], max_length=3, null=True),
        ),
    ]
